# run: conda env create --file requirements.yml
# conda env update --file requirements.yml
name: otsupgalilee
dependencies:
- python==3.10
- pip
- numpy
- matplotlib
- scipy
- jupyter
- jupyterlab
- nbconvert
- black
- pre-commit
- flake8
- spyder
- statsmodels
- openturns==1.19
- otmorris
- pip:
  - otbenchmark

