# run: conda env create --file requirements.yml
# conda env update --file requirements.yml
name: otsupgalilee
dependencies:
- python==3.13
- pip
- numpy
- matplotlib
- scipy
- jupyter
- jupyterlab
- nbconvert
- black
- pre-commit
- flake8
- spyder
- statsmodels
- tqdm
- tabulate
- openturns==1.24
- otmorris
- otbenchmark

